theme: jekyll-theme-hacker
title: R3D-Z3E:~#
description: Challenge the Defense; Strengthen the Shield.
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  - jekyll-twitter-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
